spring:
  main:
    banner-mode: off
  application:
    name: alphamart
  datasource:
    url: jdbc:h2:mem:ai-assistant-db
    username: sa
    password: password
  jackson:
    default-property-inclusion: always
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
    property-naming-strategy: KEBAB_CASE
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  # jpa:
  #   show-sql: true
  #   properties:
  #     hibernate:
  #       format_sql: true

server:
  servlet:
    context-path: /alphamart
  port: 8888

flyway:
  baselineOnMigrate: true

springdoc:
  show-actuator: true
  swagger-ui:
    enabled: true
    supported-submit-methods: []
    path: /api-docs
    tags-sorter: alpha
    operations-sorter: alpha

logging:
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(---){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %clr(%10t){magenta} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
  # level:
  #   org:
  #     hibernate:
  #       SQL: DEBUG
  #       orm:
  #         jdbc:
  #           bind: TRACE

management:
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
